installation_path:
  description: "Installation path:"
  type: string
  value: ""
methodology:
  description: "Methodology"
  type: string
  value: ""
goals:
  description: "Goals"
  type: array
  value: []
spyglass_options:
  description: "Spyglass Options"
  type: array
  value: []
rule_parameters:
  description: "Rule Parameters"
  type: array
  value: []
